build:
  environment:
    php: '5.6.9'

  dependencies:
      before:
          - 'apt-get install libimage-exiftool-perl'

  tests:
      before:
          - 'phpunit'

before_commands:
    - "composer install --no-interaction --prefer-source"
