build:
  environment:
    php: "5.6.9"

  dependencies:
      before:
          - "sudo apt-get install libimage-exiftool-perl"

  tests:
      override:
      -
          command: "phpunit --coverage-clover ./logs/coverage.clover"
          coverage:
              file: "./logs/coverage.clover"
              format: 'clover'

before_commands:
    - "composer install --no-interaction --prefer-source"
