build:
  environment:
    php:
    - '5.6.9'
    - '5.6.16'
    - '7.0.6'
    - '7.0.7'
    - '7.0.8'
    - '7.1.0'
    - 'hvm'

  dependencies:
      before:
          - 'apt-get install libimage-exiftool-perl'

  tests:
      before:
          - 'phpunit'

before_commands:
    - "composer install --no-interaction --prefer-source"
