language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

before_install:
- composer require satooshi/php-coveralls:dev-master
- composer install --dev

install:
  - composer install --no-interaction --prefer-source

addons:
  apt:
    packages:
    - libimage-exiftool-perl

script: phpunit --coverage-clover ./tests/logs/clover.xml
